Repository dji-7/repo, pull requests merged in 2021-07, with the labels that each got.

#12 pull to additional buildind solutions in: self_hosted.yml
  .github/workflows/self_hosted.yml
Labels: bug, documentation, enhancement, fixed-on-actions-in-yml-build-file, tag-feature-solutions

#19 Create README.html and fixed in typos
  READM.htm
Labels: bug, documentation, duplicate, enhancement, fixed-on-actions-in-yml-build-file, good first issue, help wanted, invalid, question, tag-feature-solutions, wontfix

#18 Up it to date in and Fixed tags typos
  README.md
Labels: enhancement, fixed-on-actions-in-yml-build-file, tag-feature-solutions

#21 add links to the blank fields
  README.md
Labels: bug, duplicate, enhancement, fixed-on-actions-in-yml-build-file, tag-feature-solutions

#25 add features to this pull request to reach issues
  template.py
Labels: blob-issues, documentation, fixed-on-actions-in-yml-build-file, tag-feature-solutions

#31 Update and improve by removed duplicates phrases
  lang.x
Labels: blob-issues, fixed-on-actions-in-yml-build-file, tag-feature-solutions

#20 build theses files is a features requesting
  README.md
  source_page.py
  template.py
Labels: blob-issues, bug, fixed-on-actions-in-yml-build-file, tag-feature-solutions

#32 pull fixing open request to achieve the right issues in fixed and organized -all
  .github/workflows/codeql-analysis.yml
  README.md
Labels: blob-issues, bug, documentation, duplicate, enhancement, fixed-on-actions-in-yml-build-file, good first issue, help wanted, invalid, question, tag-feature-solutions, wontfix

#41 Improve CNAME for current branch-name
  .github/workflows/codeql-analysis.yml
  CNAME
  README.md
Labels: blob-issues, bug, documentation, fixed-on-actions-in-yml-build-file, help wanted, tag-feature-solutions

#35 Merge pull requests to fix bug
  README.md
Labels: bug

#40 features
  .github/workflows/codeql-analysis.yml
  README.md
  lang.x
Labels: blob-issues, bug, fixed-on-actions-in-yml-build-file, tag-feature-solutions

#37 Merge abracadabra features
  README.md
  doc/README.md
Labels: blob-issues, bug, documentation, duplicate, enhancement, fixed-on-actions-in-yml-build-file, good first issue, help wanted, invalid, question, tag-feature-solutions, wontfix

#43 Trigger in -all
  README.md
Labels: blob-issues

#50 Merge feature request in (YML) to fixed bugs and solved errors
  README.md
Labels: blob-bugs, bug, documentation, duplicate, enhancement, fixed-on-actions-in-yml-build-file, good first issue, help wanted, invalid, question, tag-feature-solutions, wontfix

#49 Update by improvements between double phrases in remove duplicates
  README.md
Labels: blob-bugs, bug, documentation, duplicate, enhancement, fixed-on-actions-in-yml-build-file, tag-feature-solutions
